version: '3.9'
services:
        apache:
                image: httpd:latest
                container_name: the-curator-apache
                ports:
                        - "80:80"
                volumes:
                        - ./TheCuratorWeb:/usr/local/apache2/htdocs/