version: '3.9'
services:
   postgres:
      image: postgres:latest
      container_name: the-curator-postgres
      restart: always
      environment:
       - POSTGRES_USER=curatoradmin
       - POSTGRES_PASSWORD=curatorpassword
       - POSTGRES_DB=curatordb
      ports:
       - "5432:5432"
      volumes:
       - pgdata:/var/lib/postgresql/data
volumes:
   pgdata:
